### ISSUE TITLE
First module not found

### ISSUE THREAD

**Issue by DRAGKILLS** [xroix/MCBE-Win10-FOV-Changer#137]
the error on thread https://github.com/xroix/MCBE-Win10-FOV-Changer/blob/master/src/thread.py#L82

**Comment by xroix** [comment]
Please specify when this crash happens. Also, include the content of the crash_log.txt file, if it is indeed a crash.

**Comment by DRAGKILLS** [comment]
ok

**Comment by DRAGKILLS** [comment]
how to use from the sourcecode?
