### ISSUE TITLE
Address detection issue for overseas (JP)

### ISSUE THREAD

**Issue by yuto0214w** [xroix/MCBE-Win10-FOV-Changer#139]
Log: [crash_log.txt](https://github.com/xroix/MCBE-Win10-FOV-Changer/files/7782728/crash_log.txt)

### Description
When "Start" clicked, it ran into problem and crash for non-English user.

### Expected
Found address correctly and run

### Actual
Ran into problem `UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence`

### Fix
By setting locale "UTF-8" **or** "English/US" in control panel
Though I'm never recommending changing locale to English/US since it has adverse effects to some application.
I don't know if UTF-8 but I'm pretty sure it doesn't have adverse effects.

1. Open Control Panel and click "Change date, time, number formats"
2. Click "Administrative"
3. Click "Change system locale..."

![image](https://user-images.githubusercontent.com/46196561/147528580-e6d88675-b85d-40c2-8c07-2a36adf5e483.png)

4. Toggle "Beta: Use Unicode UTF-8 for worldwide language support"

![image](https://user-images.githubusercontent.com/46196561/147529041-b3c26a8d-f408-4107-a3fc-5293c573495f.png)

**Comment by xroix** [comment]
First, thanks for the detailed bug report!

**Comment by yuto0214w** [comment]
Thanks.
I love this application, good work! :)

**Comment by xroix** [comment]
I am currently cleaning up the issues. This was also asked in #128
