### ISSUE TITLE
FOV Changer fails to detect Minecraft then crashes

### ISSUE THREAD

**Issue by Sierrawastaken** [xroix/MCBE-Win10-FOV-Changer#143]
Upon starting FOV Changer and starting it, it prompts that Minecraft cannot be found then crashes. Attached is the [crash_log.txt](https://github.com/xroix/MCBE-Win10-FOV-Changer/files/8219283/crash_log.txt). (also there is a typo on line 13 of the crashlog "[16:56:25] > Saved version ist correct!")

**Comment by xroix** [comment]
Thank you for your report!

The "Minecraft not found" error sadly has a number of different causes. 
In your case, it deviates from #142 and it might help to delete the `storage.json` file next to the `FOV-Changer.exe`. Note that it will reset your settings, though.

If the same error still persists, you can try the steps mentioned in #142.

**Comment by xroix** [comment]
Closed for inactivity. If some encounters a similar issue, please reopen #142 instead.
