### ISSUE TITLE
forever loading

### ISSUE THREAD

**Issue by stardripp** [xroix/MCBE-Win10-FOV-Changer#145]
![image](https://user-images.githubusercontent.com/107508075/173672856-cc9f539d-4ff8-4bf8-a40c-939f19257a71.png)
ill open it and its stuck loading forever, ive tried deleting and reinstalling multiple times but nothing.

**Comment by xroix** [comment]
For those who encountered the same issue, try the following things:

- Run the FOV Changer as an admin, always
- Try out the beta, http://www.mediafire.com/file/ay5z53t9logj2wz/FOV-Changer-1.1.6-beta.zip/file

If for you, @stardripp , an other solution was the key to get it working, please let me know. (within this issue - without reopening it, though)
