### ISSUE TITLE
Couldn't communicate with the server

### ISSUE THREAD

**Issue by Stary4711** [xroix/MCBE-Win10-FOV-Changer#149]

**Comment by Yoda5577** [comment]
Hi! I'm having the same issue. I've restarted my computer, downloaded the most recent normal version, and even tried the beta but it hasn't worked. I launched it with administrator, and closed and opened both Minecraft and the FOV Changer multiple times. It only started occurring after I downloaded the most recent version, so I'm thinking Microsoft may have implemented more defenses against hacked clients, and that may have caused it to stop connecting now, I hope I've given enough information, and I also wanna say you did an amazing job with this.

**Comment by SuperLlama88888** [comment]
@Yoda5577 It says it can't communicate with the server when the server does not have the offsets for that version. It's not a "hacked client", AFAIK it changes runtime variables so is not even close to being a client at all.

**Comment by xroix** [comment]
Thanks for letting me know, and answering the question!

FOV Changer has now been updated to the latest version. So, it should be working again.
