### ISSUE TITLE
Unsupported with Minecraft v1.19.41

### ISSUE THREAD

**Issue by GraysBlock** [xroix/MCBE-Win10-FOV-Changer#150]
When trying to launch FOV Changer in Minecraft 1.19.41, the program throws an error saying "Minecraft version is unsupported!".

Actual version: '1.19.4101.0'

![image_2022-11-03_172719321](https://user-images.githubusercontent.com/70297795/199846281-df180262-e131-4f92-8efd-3ea246e133f1.png)

**Comment by xroix** [comment]
FOV Changer is now updated.
Thanks for reporting!

(Took a bit longer than usual since I didn't notice the update. I hope the wait wasn't too long.)
