### ISSUE TITLE
FOV Changer Not Connecting to Server with New Update (1.21)

### ISSUE THREAD

**Issue by notdoubtingthomas** [xroix/MCBE-Win10-FOV-Changer#166]
Hi! I recently found FOV Changer and have been using it to play MCBE on WIN10 to much satisfaction (it's awesome!), however, with the release of update 1.21 today, June 13th, FOV Changer is unable to "communicate with the server". 

Log states this: 
[18:59:40] > Attached to Minecraft!
[18:59:40] > Found MC Version '1.21.3.0'
[18:59:40] > Saved version doesn't match!
[18:59:40] > New feature offsets are needed!
[18:59:40] > Getting features for '12130'
[18:59:40] > Feature request number 0
[18:59:40] > Couldn't communicate with the server!

Would be great to see this addressed, however, I know title updates frequently cause problems with 3rd-party mods/add-ons. Thanks again for this add-on, it has been phenomenal! :) 

![Screenshot (13)](https://github.com/xroix/MCBE-Win10-FOV-Changer/assets/167242453/ff564c0e-0c23-402b-bf7b-0fb19ca5f86d)

**Comment by xroix** [comment]
Thank you for using FOV-Changer! I'm glad that you enjoy using it

This issue usually occurs when Mojang releases a new version. I have updated it and it should now work again. Just try to use it normally!
